datasets:
  meg_masc:
    data_dir: /om/data/public/language-eeg/MEG-MASC

    subjects:
      - "01"
      - "02"

    sessions:
      - 0
      - 1

    tasks:
      0: lw1
      1: cable_spool_fort
      2: easy_money
      3: the_black_willow

language_modeling:
  model: distilgpt2
  n_candidates: 1000
  vocab_path: null