from snakemake.utils import min_version
min_version("6.0")

configfile: "config.yaml"

module meg_masc:
    snakefile: "meg-masc/Snakefile"
    config: config["datasets"]["meg_masc"] | config
    prefix: "meg-masc"


use rule * from meg_masc as meg_masc_*