datasets:
  gillis2021:
    data_dir: data/gillis2021

    subjects:
      - 2019_C2DNN_11
      - 2019_C2DNN_1
      - 2019_C2DNN_12
      - 2019_C2DNN_18
      - 2019_C2DNN_2
      - 2019_C2DNN_28
      - 2019_C2DNN_29
      - 2019_C2DNN_30
      - 2019_C2DNN_32
      - 2019_C2DNN_35
      - 2019_C2DNN_36
      - 2019_C2DNN_38
      - 2019_C2DNN_45
      - 2019_C2DNN_47
      - 2019_C2DNN_48
      - 2019_C2DNN_49
      - 2019_C2DNN_5
      - 2019_C2DNN_52
      - 2019_C2DNN_54
      - 2019_C2DNN_57
      - 2019_C2DNN_6
      - 2019_C2DNN_63
      - 2019_C2DNN_64
      - 2019_C2DNN_66
      - 2019_C2DNN_69
      - 2019_C2DNN_7
      - G12A10
      - L02J10
      - V09L10

    stories:
      - DKZ_1
      - DKZ_2
      - DKZ_3

    subset_sensors:
      - C1
      - Cz
      - C2
      - CP1
      - CPz
      - CP2

    language_modeling:
      model: GroNLP/gpt2-small-dutch
      n_candidates: 20000

  heilbron2022:

    subjects:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
    stories:
      - old-man-and-the-sea
    runs:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19

    language_modeling:
      model: EleutherAI/gpt-neo-2.7B
      n_candidates: 10000

language_modeling:
  model: distilgpt2
  n_candidates: 10000

fit:
  cv_strategy:
    trf-berp-fixed: search_alpha_threshold_lambda_priorscatter
    trf-berp-cannon: search_alpha_threshold_lambda_priorscatter
    trf: search_alpha
    base_trf: search_alpha
    trf_t1: search_alpha
    trf-cannon: search_alpha
