datasets:
  gillis2021:
    data_dir: data/gillis2021

    subjects:
      - 2019_C2DNN_11
      - 2019_C2DNN_1
      - 2019_C2DNN_12
      - 2019_C2DNN_18
      - 2019_C2DNN_2
      - 2019_C2DNN_28
      - 2019_C2DNN_29
      - 2019_C2DNN_30
      - 2019_C2DNN_32
      - 2019_C2DNN_35
      - 2019_C2DNN_36
      - 2019_C2DNN_38
      - 2019_C2DNN_45
      - 2019_C2DNN_47
      - 2019_C2DNN_48
      - 2019_C2DNN_49
      - 2019_C2DNN_5
      - 2019_C2DNN_52
      - 2019_C2DNN_54
      - 2019_C2DNN_57
      - 2019_C2DNN_6
      - 2019_C2DNN_63
      - 2019_C2DNN_64
      - 2019_C2DNN_66
      - 2019_C2DNN_69
      - 2019_C2DNN_7
      - G12A10
      - L02J10
      - V09L10

    stories:
      - DKZ_1
      - DKZ_2
      - DKZ_3

    subset_sensors:
      - C1
      - Cz
      - C2
      - CP1
      - CPz
      - CP2

    language_modeling:
      model: GroNLP/gpt2-small-dutch
      n_candidates: 20000

  heilbron2022:

    subjects:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
    stories:
      - old-man-and-the-sea
    runs:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19

    language_modeling:
      model: EleutherAI/gpt-neo-2.7B
      n_candidates: 10000

    paradigms:
      wide:
        dataset_spec: heilbron_wide
        feature_spec: heilbron
      back:
        dataset_spec: heilbron_back
        feature_spec: heilbron
      cannon_wide:
        dataset_spec: heilbron_wide
        feature_spec: heilbron
      cannon_back:
        dataset_spec: heilbron_back
        feature_spec: heilbron
      back_syllable:
        dataset_spec: heilbron_back
        feature_spec: heilbron_syllable
      cannon_back_syllable:
        dataset_spec: heilbron_back
        feature_spec: heilbron_syllable

language_modeling:
  model: distilgpt2
  n_candidates: 10000

fit:
  cv_strategy:
    trf-berp-fixed: search_alpha_threshold_lambda_priorscatter
    trf-berp-fixed-t075: search_alpha_threshold_lambda_priorscatter
    trf-berp-cannon: search_alpha_threshold_lambda_priorscatter
    trf: search_alpha
    base_trf: search_alpha
    trf_t1: search_alpha
    trf-cannon: search_alpha

evaluations:
  trf_vs_baseline:
    base_model:
      paradigm: _wide
      model: base_trf
    full_model:
      paradigm: _wide
      model: trf

  shift_vs_baseline:
    base_model:
      paradigm: _wide
      model: trf
    full_model:
      paradigm: _wide
      model: trf-berp-fixed

  variable_vs_baseline:
    base_model:
      paradigm: _wide
      model: trf
    full_model:
      paradigm: _cannon_wide
      model: trf-berp-cannon_3quantiles.29720801

  variable_vs_shift:
    base_model:
      paradigm: _wide
      model: trf-berp-fixed

    full_model:
      paradigm: _cannon_wide
      model: trf-berp-cannon_3quantiles.29720801

  prior_vs_baseline:
    base_model:
      paradigm: _wide
      model: trf
    full_model:
      paradigm: _cannon_wide
      model: trf-cannon_3quantiles

  variable_vs_prior:
    base_model:
      paradigm: _cannon_wide
      model: trf-cannon_3quantiles
    full_model:
      paradigm: _cannon_wide
      model: trf-berp-cannon_3quantiles.29720801

  shift075_vs_baseline:
    base_model:
      paradigm: _wide
      model: trf
    full_model:
      paradigm: _wide
      model: trf-berp-fixed-t075

  variable_vs_shift075:
    base_model:
      paradigm: _wide
      model: trf-berp-fixed-t075

    full_model:
      paradigm: _cannon_wide
      model: trf-berp-cannon_3quantiles.29720801

  back_trf_vs_baseline:
    base_model:
      paradigm: _back
      model: base_trf
    full_model:
      paradigm: _back
      model: trf

  back_shift_vs_baseline:
    base_model:
      paradigm: _back
      model: trf
    full_model:
      paradigm: _back
      model: trf-berp-fixed-t075

  back_variable_vs_baseline:
    base_model:
      paradigm: _back
      model: trf
    full_model:
      paradigm: _cannon_back
      model: trf-berp-cannon_3quantiles

  back_variable_vs_shift:
    base_model:
      paradigm: _back
      model: trf-berp-fixed-t075
    full_model:
      paradigm: _cannon_back
      model: trf-berp-cannon_3quantiles

  back_prior_vs_baseline:
    base_model:
      paradigm: _back
      model: trf
    full_model:
      paradigm: _cannon_back
      model: trf-cannon_3quantiles

  back_variable_vs_prior:
    base_model:
      paradigm: _cannon_back
      model: trf-cannon_3quantiles
    full_model:
      paradigm: _cannon_back
      model: trf-berp-cannon_3quantiles

  back_syllable_trf_vs_baseline:
    base_model:
      paradigm: _back_syllable
      model: base_trf
    full_model:
      paradigm: _back_syllable
      model: trf