n_outer_folds: 4
n_inner_folds: 4
n_trials: 100

param_sampler:
  _target_: optuna.samplers.TPESampler
  multivariate: true

params:
  encoder__alpha:
    type: float
    low: 1e1
    high: 1e6
    log: true
    # shape: [129]

  # encoder__init_scale:
  #   type: float
  #   low: 1e-5
  #   high: 1e-1
  #   log: true

  # encoder__optim__learning_rate:
  #   type: float
  #   low: 1e-4
  #   high: 5e-1
  #   log: true

  threshold:
    type: float
    low: 0.0
    high: 1.0

  lambda_:
    type: float
    low: 0.1
    high: 3
