n_outer_folds: 4
n_inner_folds: 4

param_sampler:
  _target_: optuna.samplers.TPESampler
  multivariate: true

params:
  encoder__alpha:
    type: float
    low: 1e5
    high: 1e7
    log: true
    # shape: [129]

  # encoder__optim__learning_rate:
  #   type: float
  #   low: 1e-4
  #   high: 5e-1
  #   log: true