n_outer_folds: 4
n_inner_folds: 4

n_trials: 50

param_sampler:
  _target_: optuna.samplers.TPESampler
  multivariate: true

sensor_aggregation_fn: max

params:
  encoder__alpha:
    type: float
    low: 1e4
    high: 1e6
    log: true
    # shape: [129]

  # encoder__optim__learning_rate:
  #   type: float
  #   low: 1e-4
  #   high: 5e-1
  #   log: true