n_outer_folds: 4
n_inner_folds: 4
n_trials: 500

param_sampler:
  _target_: optuna.samplers.TPESampler
  multivariate: true

params:
  encoder__alpha:
    type: float
    low: 1e2
    high: 1e6
    log: true
    # shape: [129]

  threshold:
    type: float
    low: 0.0
    high: 1.0

  lambda_:
    type: float
    low: 0.1
    high: 3

  prior_scatter_index:
    type: categorical
    choices:
      - 0
      - -1
      - -2
      - -3

  variable_trf_zero_left:
    type: int
    low: 0
    high: 36

  variable_trf_zero_right:
    type: int
    low: 0
    high: 36